### ISSUE TITLE
Failed to Create All possible pairs

### ISSUE THREAD

**Issue by LukeActon** [BioinformaticsLabAtMUN/sRNARFTarget#2]
Hi there,

Im trying to use sRNARFTarget using a virtual machine. At the moment im just using the Ecoli dataset providedin the github repository. 
When I run the .nf script, it always fails creating all possible pairs.

Error executing process > 'createAllPossiblePairs'

Caused by:
  Process `createAllPossiblePairs` terminated with an error exit status (1)

Im running the programme with the Docker container provided, any idea whats causing this? 

Thanks!

**Comment by LukeActon** [comment]
[.command.log](https://github.com/BioinformaticsLabAtMUN/sRNARFTarget/files/7890154/default.command.log)

Seems like im unable to create symbolic links, do you know of a work around for this?

**Comment by BioinformaticsLabAtMUN** [comment]
Hello,

What operating system are you using? and do you have permissions to write
on the directory nextflow is creating the work directory?

Best,

**Comment by LukeActon** [comment]
Hi there
Many thanks for getting back to me!

Im using a linux virtual machine, connected to a HPC

I do have permission to write on the directory im using.

**Comment by BioinformaticsLabAtMUN** [comment]
I  think the issue may be with the virtual machine and not with sRNARFTarget.

Based on these posts: https://kb.vmware.com/s/article/1007277 and https://www.speich.net/articles/en/2018/12/24/virtualbox-6-how-to-enable-symlinks-in-a-linux-guest-os/  It seems virtual machines may not allow symbolic links.

Try checking whether symbolic links are enabled on your virtual machine.
